export const GET_SUPPORT_ADD_UPDATE = 'GET_SUPPORT_ADD_UPDATE';
export const GET_SUPPORT_ADD_UPDATE_SUCCESS = 'GET_SUPPORT_ADD_UPDATE_SUCCESS';
export const GET_SUPPORT_ADD_UPDATE_ERROR = 'GET_SUPPORT_ADD_UPDATE_ERROR';
