export const GET_SUPPORT_ID_DATA = 'GET_SUPPORT_ID_DATA';
export const GET_SUPPORT_ID_DATA_SUCCESS = 'GET_SUPPORT_ID_DATA_SUCCESS';
export const GET_SUPPORT_ID_DATA_ERROR = 'GET_SUPPORT_ID_DATA_ERROR';
