export const GET_HOLIDAY_ID_DATA = 'GET_HOLIDAY_ID_DATA';
export const GET_HOLIDAY_ID_DATA_SUCCESS = 'GET_HOLIDAY_ID_DATA_SUCCESS';
export const GET_HOLIDAY_ID_DATA_ERROR = 'GET_HOLIDAY_ID_DATA_ERROR';
