export const GET_HOLIDAY_ADD_UPDATE = 'GET_HOLIDAY_ADD_UPDATE';
export const GET_HOLIDAY_ADD_UPDATE_SUCCESS = 'GET_HOLIDAY_ADD_UPDATE_SUCCESS';
export const GET_HOLIDAY_ADD_UPDATE_ERROR = 'GET_HOLIDAY_ADD_UPDATE_ERROR';
