export const GET_LEAVE_ADD_UPDATE = 'GET_LEAVE_ADD_UPDATE';
export const GET_LEAVE_ADD_UPDATE_SUCCESS = 'GET_LEAVE_ADD_UPDATE_SUCCESS';
export const GET_LEAVE_ADD_UPDATE_ERROR = 'GET_LEAVE_ADD_UPDATE_ERROR';
