export const GET_CHANGE_PASSWORD = 'GET_CHANGE_PASSWORD';
export const GET_CHANGE_PASSWORD_SUCCESS = 'GET_CHANGE_PASSWORD_SUCCESS';
export const GET_CHANGE_PASSWORD_ERROR = 'GET_CHANGE_PASSWORD_ERROR';
