export const GET_EXPENSE_ID_DATA = 'GET_EXPENSE_ID_DATA';
export const GET_EXPENSE_ID_DATA_SUCCESS = 'GET_EXPENSE_ID_DATA_SUCCESS';
export const GET_EXPENSE_ID_DATA_ERROR = 'GET_EXPENSE_ID_DATA_ERROR';
