export const GET_EXPENSE_ADD_UPDATE = 'GET_EXPENSE_ADD_UPDATE';
export const GET_EXPENSE_ADD_UPDATE_SUCCESS = 'GET_EXPENSE_ADD_UPDATE_SUCCESS';
export const GET_EXPENSE_ADD_UPDATE_ERROR = 'GET_EXPENSE_ADD_UPDATE_ERROR';
