export const GET_EMPLOYEE_CHANGE_PASSWORD = 'GET_EMPLOYEE_CHANGE_PASSWORD';
export const GET_EMPLOYEE_CHANGE_PASSWORD_SUCCESS = 'GET_EMPLOYEE_CHANGE_PASSWORD_SUCCESS';
export const GET_EMPLOYEE_CHANGE_PASSWORD_ERROR = 'GET_EMPLOYEE_CHANGE_PASSWORD_ERROR';
