export const GET_EMPLOYEE_UPDATE = 'GET_EMPLOYEE_UPDATE';
export const GET_EMPLOYEE_UPDATE_SUCCESS = 'GET_EMPLOYEE_UPDATE_SUCCESS';
export const GET_EMPLOYEE_UPDATE_ERROR = 'GET_EMPLOYEE_UPDATE_ERROR';
