export const GET_EMPLOYEE_DISABLE = 'GET_EMPLOYEE_DISABLE';
export const GET_EMPLOYEE_DISABLE_SUCCESS = 'GET_EMPLOYEE_DISABLE_SUCCESS';
export const GET_EMPLOYEE_DISABLE_ERROR = 'GET_EMPLOYEE_DISABLE_ERROR';
