export const GET_EMPLOYEE_DELETE = 'GET_EMPLOYEE_DELETE';
export const GET_EMPLOYEE_DELETE_SUCCESS = 'GET_EMPLOYEE_DELETE_SUCCESS';
export const GET_EMPLOYEE_DELETE_ERROR = 'GET_EMPLOYEE_DELETE_ERROR';
