export const GET_EMPLOYEE_BY_SLUG = 'GET_EMPLOYEE_BY_SLUG';
export const GET_EMPLOYEE_BY_SLUG_SUCCESS = 'GET_EMPLOYEE_BY_SLUG_SUCCESS';
export const GET_EMPLOYEE_BY_SLUG_ERROR = 'GET_EMPLOYEE_BY_SLUG_ERROR';
