export const BASE_URL = process.env.REACT_APP_API_BASE_URL;

export const API_URL = {
  LOGIN_URL: '/login',
  FORGOT_PASSWORD_URL: '/forgot-password',
  RESET_PASSWORD_URL: '/reset-forgot-password',
  ORGANISATION_SIGNUP_URL: '/admin/signup',
  DOMAIN_URL: '/check/domain',
  PROFIlE_SETUP_URL: '/profile-setup',
  PROFIlE_UPDATE_URL: '/profile',
  DASHBOARD_URL: '/dashboard',
  EMPLOYEE_LIST_URL: '/admin/user',
  EMPLOYEE_ADD_URL: '/user/signup',
  EMPLOYEE_BY_SLUG_URL: '/',
  EMPLOYEE_UPDATE_URL: '/admin/employee',
  EMPLOYEE_DELETE_URL: '/admin/delete',
  EMPLOYEE_CHANGE_PASSWORD_URL: '/admin/change-password',
  SUPPORT_ADD_UPDATE_URL: '/user/support-ticket',
  SUPPORT_GET_URL: '/support-ticket/list',
  SUPPORT_BY_ID_URL: '/support-ticket',
  SUPPORT_DELETE_URL: '/user/support-ticket',
  SUPPORT_REASON_URL: '/admin/support-ticket/status',
  PAYSLIP_LIST_URL: '/payslip/list',
  ATTENDANCE_LIST_URL: '/attendance/list',
  EXPENSE_ADD_UPDATE_URL: '/user/expense',
  EXPENSE_DELETE_URL: '/user/expense',
  EXPENSE_LIST_URL: '/expense',
  EXPENSE_BY_ID_URL: '/expense',
  EXPENSE_REASON_URL: '/admin/expense/action',
  HOLIDAY_LIST_URL: '/holiday/list',
  HOLIDAY_ADD_UPDATE_URL: '/admin/holiday',
  HOLIDAY_BY_ID_URL: '/admin/holiday',
  HOLIDAY_DELETE_URL: '/admin/holiday',
  CHANGE_PASSWORD_URL: '/user/change-password',
  LEAVE_ADD_UPDATE_URL: '/user/leave',
  LEAVE_LIST_URL: '/leave',
  LEAVE_DELETE_URL: '/user/leave',
  LEAVE_REASON_URL: '/admin/leave/status',
  LEAVE_BY_ID_URL: '/leave'
};
