export const GET_ATTENDANCE_LIST = 'GET_ATTENDANCE_LIST';
export const GET_ATTENDANCE_LIST_SUCCESS = 'GET_ATTENDANCE_LIST_SUCCESS';
export const GET_ATTENDANCE_LIST_ERROR = 'GET_ATTENDANCE_LIST_ERROR';
