export const GET_TIME_ACTIVITY_REPORT_LIST = 'GET_TIME_ACTIVITY_REPORT_LIST';
export const GET_TIME_ACTIVITY_REPORT_LIST_SUCCESS = 'GET_TIME_ACTIVITY_REPORT_LIST_SUCCESS';
export const GET_TIME_ACTIVITY_REPORT_LIST_ERROR = 'GET_TIME_ACTIVITY_REPORT_LIST_ERROR';
