export const GET_TIME_ACTIVITY_ID_DATA = 'GET_TIME_ACTIVITY_ID_DATA';
export const GET_TIME_ACTIVITY_ID_DATA_SUCCESS = 'GET_TIME_ACTIVITY_ID_DATA_SUCCESS';
export const GET_TIME_ACTIVITY_ID_DATA_ERROR = 'GET_TIME_ACTIVITY_ID_DATA_ERROR';
