export const GET_ORGANISATION_SIGNUP = 'GET_ORGANISATION_SIGNUP';
export const GET_ORGANISATION_SIGNUP_SUCCESS = 'GET_ORGANISATION_SIGNUP_SUCCESS';
export const GET_ORGANISATION_SIGNUP_ERROR = 'GET_ORGANISATION_SIGNUP_ERROR';
