export const GET_PROFILE_UPDATE = 'GET_PROFILE_UPDATE';
export const GET_PROFILE_UPDATE_SUCCESS = 'GET_PROFILE_UPDATE_SUCCESS';
export const GET_PROFILE_UPDATE_ERROR = 'GET_PROFILE_UPDATE_ERROR';

export const GET_ORGANISATION_PROFILE_UPDATE = 'GET_ORGANISATION_PROFILE_UPDATE';
export const GET_ORGANISATION_PROFILE_UPDATE_SUCCESS = 'GET_ORGANISATION_PROFILE_UPDATE_SUCCESS';
export const GET_ORGANISATION_PROFILE_UPDATE_ERROR = 'GET_ORGANISATION_PROFILE_UPDATE_ERROR';
