# This is a basic workflow to help you get started with Actions

name: Deploy to Stage
'on':
  push:
    branches:
      - stage
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage branch
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Install Dependency
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile
      - name: Copy env
        run: cp .env.test .env
      - name: Validate Code Style
        run: yarn check-all
      - name: Build
        run: CI=false yarn build
      - name: Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }}
          debug: true
          script: |
            cd jbt-timer-web
            yarn stage-setup
