# This is a basic workflow to help you get started with Actions

name: Deploy to Stage
'on':
  push:
    branches:
      - stage
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependency
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile
      - name: Copy config
        run: cp .env.test .env
      - name: Validate Code Style
        run: yarn check-all
      - name: Build
        run: CI=false yarn build
      - name: Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd jbt-timer/jbt-timer-web
            yarn setup
