# This is a basic workflow to help you get started with Actions

name: Deploy to Stage
'on':
  push:
    branches:
      - stage
jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd jbt-timer-web
        yarn install
        yarn build