name: Deploy to Stage
'on':
  push:
    branches:
      - stage
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'

      - name: Web => Restore Cache
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Web => Install Dependency
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile

      - name: Setup ENV
        run: cp .env.test .env

      - name: Validate Code Style
        run: yarn check-all

      - name: Web => Build
        run: CI=false yarn build

      - name: Web => Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }}
          debug: true
          script: |
            whoami
            cd jbt-timer-web
            yarn stage-setup
