name: Deploy to Stage
'on':
  push:
    branches:
      - stage
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage branch
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependency
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile
      - name: Validate Code Style
        run: yarn check-all
      - name: Build
        run: CI=false yarn build:stage
      - name: Deploy Code
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./build/*
          target: ~/jbt-timer-web/
  
      #- name: Deploy Code
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.SERVER_HOST }}
      #    username: ${{ secrets.SERVER_USER }}
      #    password: ${{ secrets.SERVER_PASS }}
      #    debug: true
      #    script: |
      #      cd jbt-timer-web
      #      bash script/stage-setup.sh
